name: Rust

permissions:
    contents: read


on:
    push:
        branches: [master]

    workflow_dispatch:


jobs:
    build-and-run:
        runs-on: [self-hosted, linux, x64]
        steps:
            - name: checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
            
            - name: set-permissions
              run: chmod u+x *.sh

            - name: build
              run: ./build.sh

            - name: run
              run: ./run.sh
