name: Rust

permissions:
  contents: read

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0

      - name: cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #v6.1.0
        env:
          cache-name: cargo-cache
        with:
          path: ./build
          key: ${{ runner.os }}-${{ env.cache-name }}

      - name: set-permissions
        run: chmod u+x *.sh

      - name: build
        run: ./build.sh

      - name: run
        run: ./run.sh
